---
- name: Clean
  hosts: all
  vars:
    ccleaner_path: 'C:\Program Files\CCleaner\CCleaner64.exe'
  tasks:
    - name: ccleaner
      win_shell: "{{ ccleaner_path }} /AUTO"
      #args:
       # executable: cmd.exe
      debug:
        msg: Path is {{ ccleaner_path }}
    