---
- name: Upgrade_Install Base Applications
  hosts: all
  tasks:

## Chocolatey cannot tell if the app was removed by ccleaner or another program
## it relies on the DB in the chocolatey folder in ProgramData, not the registry.

## This snippet uses a registry check to determine if the application is installed, then stores
## the results in the var.

## VLC
    - name: Check for VLC
      win_reg_stat:
        path: HKLM:\SOFTWARE\VideoLAN\VLC
      register: vlc_installed
    - name: Show Results
      debug:
        var: vlc_installed.exists
 
## This snippet checks against the var results from the previous registry check.  If the reg key 
## is NOT present to force the installation of the app.  If the reg key IS present, to do an 
## upgrade to the latest version.

    - name: Ensure VLC is intalled or updated.
      win_chocolatey:
        name: vlc
        state: latest
        force: "{{ 'yes' if vlc_installed.exists == false else 'no' }}"
      register: update_result

    - name: Check for ccleaner
      win_reg_stat:
        path: HKLM:\SOFTWARE\Piriform\CCleaner
      register: ccleaner_installed
    - name: Show Results
      debug:
        var: ccleaner_installed.exists
    - name: Ensure CCleaner is intalled or updated.
      win_chocolatey:
        name: ccleaner
        state: latest
        force: "{{ 'yes' if ccleaner_installed.exists == false else 'no' }}"
      register: update_result

## 7Zip

    - name: Check for 7ZIP
      win_reg_stat:
        path: HKLM:\SOFTWARE\7-Zip
      register: zip_installed
    - name: Show Results
      debug:
        var: zip_installed.exists
    - name: Ensure 7-Zip is intalled or updated.
      win_chocolatey:
        name: 7zip.install
        state: latest
        force: "{{ 'yes' if zip_installed.exists == false else 'no' }}"
      register: update_result

## PuTTy

    - name: Check for PuTTY
      win_reg_stat:
        path: HKLM:\SOFTWARE\SimonTatham\PuTTY64
      register: putty_installed
    - name: Show Results
      debug:
        var: putty_installed.exists
    - name: Ensure PuTTY is intalled or updated.
      win_chocolatey:
        name: putty.install
        state: latest
        force: "{{ 'yes' if putty_installed.exists == false else 'no' }}"
      register: update_result

## Avast

    - name: Check for Avast
      win_reg_stat:
        path: HKLM:\SOFTWARE\Wow6432Node\Avast Software\Avast
      register: avast_installed
    - name: Show Results
      debug:
        var: avast_installed.exists
    - name: Ensure Avast is intalled or updated.
      win_chocolatey:
        name: avastfreeantivirus
        state: latest
        force: "{{ 'yes' if avast_installed.exists == false else 'no' }}"
      register: update_result
