- hosts: all
  tasks:
    - name: Install missing updates with reboot.
      win_updates:
        category_names:
        - CriticalUpdates
        - SecurityUpdates
        - UpdateRollups
        reboot: yes

