- hosts: localhost
  connection: localhost
  tasks:
  - name: Gather all registered VM's
    delegate_to: localhost
    ESXi:
    vmware_vm_facts:
      validate_certs: false
      
## Ensure to use your VMWare Cloud Credential (VMware vCenter) with the Job template. 
## Currently the job template requires a Machine Credential, create a blank Machine Credential
## to use in addition to the VMWare Cloud Credential.

      username: "{{ lookup('env', 'VMWARE_USER') }}"
      password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
      hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    register: vmfacts

  - debug:
      var: vmfacts.virtual_machines
