- hosts: localhost
  gather_facts: yes
  tasks:
  - name: Gather all registered virtual machines
    delegate_to: localhost
    vmware_vm_inventory:
      hostname: "{{ ansible_env.VMWARE_HOST }}"
      username: "{{ ansible_env.VMWARE_USER }}"
      password: "{{ ansible_env.VMWARE_PASSWORD }}"
      validate_certs: no
      with_tags: yes


