- hosts: localhost
  connection: localhost
  tasks:
  - name: Gather all registered VM's
    delegate_to: localhost
    ESXi:
    vmware_vm_facts:
      validate_certs: false
      username: "{{ lookup('env', 'VMWARE_USER') }}"
      password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
      hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    register: vmfacts

  - debug:
      var: vmfacts.virtual_machines
