- hosts: localhost
  tasks:
    - name: Gather all registered virtual machines
      vmware_guest_facts:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: ha-datacenter
        validate_certs: no
      delegate_to: localhost
      register: vmfacts

    - debug:
        var: vmfacts.virtual_machines
