- hosts: localhost
  connection: localhost
  tasks:
  - name: Gather all registered VM's
    delegate_to: localhost
    ESXi:
    vmware_guest_facts:
      validate_certs: false
      
## Ensure to use your VMWare Cloud Credential (VMware vCenter) with the Job template. 
## Currently the job template requires a Machine Credential, create a blank Machine Credential
## to use in addition to the VMWare Cloud Credential.

      username: "{{ lookup('env', 'VMWARE_USER') }}"
      password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
      hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
      datacenter: ha-datacenter
      folder: /ha-datacenter/vm
        
## For each Host in the Inventory, retrieves Name and UUID from the Hosts Variables.
      name: "{{ config.name }}"
      uuid: "{{ config.uuid }}"
    register: vmfacts

  - debug:
      var: vmfacts.virtual_machines
