- hosts: localhost
  connection: localhost
  vars:
    vault_credential: "{{ vcenter_pass }}"
  tasks:
  - name: Gather all registered VM's
    delegate_to: localhost
    ESXi:
    vmware_vm_facts:
      validate_certs: false
      username: administrator@vsphere.local
      password: !vault | "{{ vcenter_pass }}"
      hostname: 192.168.2.55
    register: vmfacts

  - debug:
      var: vmfacts.virtual_machines
